# Generated by Django 6.0.2 on 2026-02-22 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_info', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='fist_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='list_name',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='file',
            new_name='profile_pic',
        ),
        migrations.AlterField(
            model_name='student',
            name='country',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(max_length=10),
        ),
    ]
